spring:
  jackson:
    default-property-inclusion: always
  boot:
    admin:
      client:
        url: http://localhost:9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    #hostname: localhost
management:
  endpoints:
    web:
      exposure:
          include: '*'
keycloak:
  realm: cloud
  auth-server-url: http://keycloak:9100/auth
  #auth-server-url: http://localhost:9100/auth
  resource: cloud-service
  public-client: true
opentracing:
  jaeger:
    udp-sender:
      host: jaeger-server
      port: 6831
