server:
  port: 9002
spring:
  cloud:
    stream:
      bindings:
        products-out-0:
          destination: products
      kafka:
        binder:
          brokers: kafka:9092
          #brokers: localhost:9092