scrape_configs:
  - job_name: 'shop'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['shop:9000']
rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-server:9093