POST http://localhost:8000/users
Content-Type: application/json
Accept: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski"
}

###

GET http://localhost:8000/users/2
Content-Type: application/json
Accept: application/json