POST http://localhost:9000/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "5 PLN",
  "additionalInfo": {
    "cardNumber": "1234567789",
    "cvv": 255
  }

}

###

GET http://localhost:9000/payments/9a0a5d31-59ec-4cc3-a50f-d3a5db72e3339
Accept: application/json
Content-Type: application/json

###

POST http://localhost:9000/orders
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "entries": {
    "1": 2,
    "2": 5
  }
}

###

GET https://fullstack-developer.io/api-dev/products?_start=0&_limit=10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjM3NTgwMjQ1LCJleHAiOjE2NDAxNzIyNDV9.lTfYjtwdnvvlxuG7o3V468KFLSxkq8XemblFS49yvcQ

###

GET https://fullstack-developer.io/api-dev/products/count

###

POST https://fullstack-developer.io/api-dev/auth/local
Accept: application/json
Content-Type: application/json

{
  "identifier": "training@sages.pl",
  "password": "P@ssw0rd"
}

###

POST http://localhost:9001/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "100 PLN"
}

###

GET http://localhost:8888/application-default.yml

###

GET http://localhost:8888/application-default.properties

###

GET http://localhost:8888/application-development.yml

###

GET http://localhost:8888/shop-service-default.yml

###

GET http://localhost:8888/shop-service-development.yml

###

GET http://localhost:8888/discovery-server-development.yml

###

GET http://localhost:9002/products
Accept: application/xml
Content-Type: application/json

###

GET http://localhost:9002/products/1
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/api/shop/orders
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "entries": {
    "1": 2,
    "2": 5
  }
}

###

POST http://localhost:9002/products
Accept: application/json
Content-Type: application/json












