version: '3'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/database
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/postgres:/database
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@training.pl
      - PGADMIN_DEFAULT_PASSWORD=admin
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "postgres"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      DB_DATABASE: "training"
    ports:
      - "9100:8080"