spring:
  application:
    name: shop-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: master # default
  datasource:
    url: jdbc:postgresql://localhost:5432/training
  profiles:
    active: development