apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-server-rc
  namespace: training
spec:
  replicas: 5
  selector:
    app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
      namespace: training
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 3
            timeoutSeconds: 2 
