apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-one
  namespace: training
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: gfs-svc
    path: gv0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-two
  namespace: training
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: gfs-svc
    path: gv0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-three
  namespace: training
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: gfs-svc
    path: gv0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-four
  namespace: training
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: gfs-svc
    path: gv0
    readOnly: false

  
